### ISSUE TITLE
Do not crash if given pure Python wheels

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/wheel-matrix#1]
`wheel-matrix` crashes when given a package with pure Python wheels:

```
Traceback (most recent call last):
  File "/home/mauve/dev/wheel-matrix/.venv/bin/wheel-matrix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mauve/dev/wheel-matrix/wheel_matrix.py", line 162, in main
    defopt.run(identify_wheels)
  File "/home/mauve/dev/wheel-matrix/.venv/lib/python3.11/site-packages/defopt.py", line 356, in run
    return call()
           ^^^^^^
  File "/home/mauve/dev/wheel-matrix/wheel_matrix.py", line 127, in identify_wheels
    os, arch = get_os_arch(tag.platform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mauve/dev/wheel-matrix/wheel_matrix.py", line 59, in get_os_arch
    raise ValueError(f'Unknown wheel target {tag}')
ValueError: Unknown wheel target any
```

Given the intention of the tool is to report on binary wheels, it could simply exit with an error, but it would be nicer to do some analysis. For example, it could show `py2` vs `py3` etc. (not that py2 matters any more, but the wheels do exist).

**Comment by lordmauve** [comment]
Fixed in #11
