### ISSUE TITLE
Unknown architecture for macosx_10_9_universal2

### ISSUE THREAD

**Issue by hynek** [lordmauve/wheel-matrix#3]
Hi Daniel, wheel-matrix crashes on my only binary package:

```console
$ pipx run wheel-matrix argon2-cffi-bindings
Traceback (most recent call last):
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/bin/wheel-matrix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 162, in main
    defopt.run(identify_wheels)
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/defopt.py", line 356, in run
    return call()
           ^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 127, in identify_wheels
    os, arch = get_os_arch(tag.platform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 58, in get_os_arch
    return 'mac', get_arch(tag)
                  ^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 44, in get_arch
    raise ValueError(f'Unknown architecture for {tag}')
ValueError: Unknown architecture for macosx_10_9_universal2
```

**Comment by lordmauve** [comment]
Ah, I had spotted some universal2 wheels for Mac and hasn't yet worked out what they do. I'll look into this.

**Comment by lordmauve** [comment]
I found [a video by @asottile](https://youtu.be/utdohIoR9ZM?si=w8arX_5b5Rf95DDV) that explains what `universal2` wheels are but I still haven't found a PEP or some authoritative documentation.

**Comment by lordmauve** [comment]
Fixed in 0.2.0.

I implemented what @asottile's video suggested and will keep looking for a real spec.

**Comment by lordmauve** [comment]
@hynek, btw, it looks like argon2-cffi-bindings could use my workflow: https://github.com/lordmauve/pyfxr/blob/main/.github/workflows/backfill_wheels.yml

I'm going to make a reusable workflow based on wheel-matrix if you're happy to wait.

**Comment by hynek** [comment]
are you still playing :D

```
 pipx run --no-cache wheel-matrix can-ada
Traceback (most recent call last):
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/bin/wheel-matrix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 171, in main
    defopt.run(identify_wheels)
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/defopt.py", line 356, in run
    return call()
           ^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 136, in identify_wheels
    for os, arch in get_os_arches(tag.platform):
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 51, in get_os_arches
    return 'linux', get_arch(tag)
                    ^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx/.cache/b3b98fe9b4d8397/lib/python3.12/site-packages/wheel_matrix.py", line 45, in get_arch
    raise ValueError(f'Unknown architecture for {tag}')
ValueError: Unknown architecture for manylinux2014_ppc64le
```

**Comment by hynek** [comment]
> @hynek, btw, it looks like argon2-cffi-bindings could use my workflow: https://github.com/lordmauve/pyfxr/blob/main/.github/workflows/backfill_wheels.yml
> 
> I'm going to make a reusable workflow based on wheel-matrix if you're happy to wait.

I don't think I do and the output of this tool also isn't super useful because I use the limited C API which makes my wheels (mostly) compatible across Python versions.

**Comment by lordmauve** [comment]
Oh, well that's #2, but I assumed I was crashing on abi3 wheels, not misreporting them.

**Comment by lordmauve** [comment]
@hynek Ok, `argon2-cffi-bindings` is clean as of 0.3.0. I'll open a new issue for `can-ada`.
